acantril/learn-cantrill-io-labs

aws-patch-manager/02_LABINSTRUCTIONS/STAGE3 - On-Prem Managed Instances.md

I believe that in the 3rd stage of the demo, the 3F is for installing the ssm agent on the windows EC2 instance

fix: patch manager stage 3 instruction 3F title

---

aws-elastic-wordpress-evolution/02_LABINSTRUCTIONS/STAGE5 - Add an ELB and ASG.md

Updated to remove extra duplicate lines.

Update STAGE5 - Add an ELB and ASG.md

---

aws-patch-manager/02_LABINSTRUCTIONS/STAGE2 - AWS Managed Instances.md
aws-patch-manager/02_LABINSTRUCTIONS/STAGE3 - On-Prem Managed Instances.md
aws-patch-manager/02_LABINSTRUCTIONS/STAGE4 - Configure Patching.md

- Updated steps according to the new AWS console
- Fix casing
- Fix steps readability

modified steps to increase readability

---

aws-elastic-wordpress-evolution/02_LABINSTRUCTIONS/STAGE4 - Add EFS and Update the LT.md

Changed some minor spellings and changed last line to STAGE 5 (from STAGE 4).

Update STAGE4 - Add EFS and Update the LT.md

---

aws-elastic-wordpress-evolution/02_LABINSTRUCTIONS/STAGE3 - Add RDS and Update the LT.md

Changed:
You can now move onto STAGE 3
To:
You can now move onto STAGE 4

Update STAGE3 - Add RDS and Update the LT.md

---

00-aws-simple-demos/aws-lambda-vpc-efs/02_LABINSTRUCTIONS/VPC Lambda EFS Demo.md

Update VPC Lambda EFS Demo.md

---

aws-elastic-wordpress-evolution/02_LABINSTRUCTIONS/STAGE1 - Setup and Manual wordpress build.md

"Enable T2/T3" is changed to "Credit Specification" since the name in the new UI.

Corrected name as per new UI

---

aws-dms-database-migration/02_LABINSTRUCTIONS/STAGE1 - Provision Environment and Review Architecture.md

Update STAGE1 - Provision Environment and Review Architecture.md

---

aws-dms-database-migration/02_LABINSTRUCTIONS/STAGE2 - Establish network connectivity.md

Corrected the number of stages listed.

Update STAGE2 - Establish network connectivity.md

---

aws-dms-database-migration/02_LABINSTRUCTIONS/STAGE3 - Create & Configure the AWS Side infrastructure.md

Updated instructions to restart the httpd service after permission changes and added option to use systemctl command to restart ssh service.

Update STAGE3 - Create & Configure the AWS Side infrastructure.md

---

aws-dms-database-migration/02_LABINSTRUCTIONS/STAGE4 - Migrate Database & Cutover.md

The AWS User Interfaces has changed in two places:
* User must select "Provide access information manually" from the choices labelled " Access to endpoint database"
* Table mappings - "Guided UI" is now labelled "Wizard"

Updated the to reflect changes to the AWS UI

---

aws-patch-manager/02_LABINSTRUCTIONS/STAGE2 - AWS Managed Instances.md

Proposing changes as Managed instances moved to "Fleet Manager"

Update STAGE2 - AWS Managed Instances.md

---

aws-dms-database-migration/02_LABINSTRUCTIONS/STAGE4 - Migrate Database & Cutover.md

Lowest instance type available in the dropdown is now dms.t3.micro in US-EAST-1.

Update STAGE4 - Migrate Database & Cutover.md

---

aws-elastic-wordpress-evolution/02_LABINSTRUCTIONS/STAGE3 - Add RDS and Update the LT.md
aws-elastic-wordpress-evolution/02_LABINSTRUCTIONS/STAGE4 - Add EFS and Update the LT.md

Added sudo where needed
Fixes spelling

Minor instruction fixes

---

aws-patch-manager/01_LABSETUP/PatchManagerBase.yaml

Pull Windows Server AMI ID from parameter store public param.

---

aws-elastic-wordpress-evolution/02_LABINSTRUCTIONS/STAGE5 - Add an ELB and ASG.md

Update STAGE5 - Add an ELB and ASG.md - fixing some typos

---

aws-elastic-wordpress-evolution/02_LABINSTRUCTIONS/STAGE1 - Setup and Manual wordpress build.md

Added sudo to the command bash

Update STAGE1 - Setup and Manual wordpress build.md

---

AWS_HYBRID_AdvancedVPN/02_INSTRUCTIONS/STAGE4 - BGP ROUTING AND TESTING.md

Update STAGE4 - BGP ROUTING AND TESTING.md

---

aws-codepipeline-catpipeline/02_LABINSTRUCTIONS/STAGE2-CODEBUILD.md

docs: minor changes to doc.

---

aws-hybrid-activedirectory/01_LABSETUP/01_HYBRIDDIR.yaml
aws-hybrid-activedirectory/02_LABINSTRUCTIONS/STAGE2 - Connect to the ONPREMISES Jumpbox.md
aws-hybrid-activedirectory/02_LABINSTRUCTIONS/STAGE3 - Create Managed Microsoft AD within AWS.md
aws-hybrid-activedirectory/02_LABINSTRUCTIONS/STAGE4 - Create Trust.md
aws-hybrid-activedirectory/02_LABINSTRUCTIONS/STAGE5 - Create FSx and Migrate data.md
aws-hybrid-activedirectory/02_LABINSTRUCTIONS/STAGE6 - Create workspace and migrate desktop.md

Fixes 
* Duplicate metadata in Primary CFN template
* Update EC2 launch instance from old UI to new UI
* Add "network credentials" pop up in stage4 ([As commented by Liam Fitzpatrick](https://techstudyslack.slack.com/archives/C013DMSL9JS/p1670330940970549?thread_ts=1670289294.112039&cid=C013DMSL9JS)) 
* Update for UI changes on Workspaces and change from "Admin" to creating an "A4LAdmin" user due to error "You cannot create a workspace for a service account" ([As commented by Liam Fitzpatrick](https://techstudyslack.slack.com/archives/C013DMSL9JS/p1670337504494859?thread_ts=1670289294.112039&cid=C013DMSL9JS))

Updates to beta hybrid active directory

---

aws-hybrid-activedirectory/02_LABINSTRUCTIONS/STAGE3 - Create Managed Microsoft AD within AWS.md

Updated typo in SG Name

---

aws-elastic-wordpress-evolution/02_LABINSTRUCTIONS/STAGE2 - Automate the build using a Launch Template.md

Just a slight spelling correction on line 25.

Update STAGE2 - Automate the build using a Launch Template.md

---

00-aws-simple-demos/aws-systems-manager/readme.md

Adding a link to the list of supported OS's for Patch Manager.

Add list of supported OSs

---

aws-elastic-wordpress-evolution/02_LABINSTRUCTIONS/STAGE4 - Add EFS and Update the LT.md

Fix typo in Update STAGE4 - Add EFS and Update the LT.md

---

aws-elastic-wordpress-evolution/02_LABINSTRUCTIONS/STAGE5 - Add an ELB and ASG.md

Fix typo in Update STAGE5 - Add an ELB and ASG.md
